{
    "url": "https://api.github.com/repos/pallets/flask/issues/1825",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/1825/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/1825/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/1825/events",
    "html_url": "https://github.com/pallets/flask/issues/1825",
    "id": 157384306,
    "node_id": "MDU6SXNzdWUxNTczODQzMDY=",
    "number": 1825,
    "title": "Flask 0.11/httpbin: TypeError: <generator object MultiDict.lists at ...> is not JSON serializable",
    "user": {
        "login": "The-Compiler",
        "id": 625793,
        "node_id": "MDQ6VXNlcjYyNTc5Mw==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/625793?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/The-Compiler",
        "html_url": "https://github.com/The-Compiler",
        "followers_url": "https://api.github.com/users/The-Compiler/followers",
        "following_url": "https://api.github.com/users/The-Compiler/following{/other_user}",
        "gists_url": "https://api.github.com/users/The-Compiler/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/The-Compiler/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/The-Compiler/subscriptions",
        "organizations_url": "https://api.github.com/users/The-Compiler/orgs",
        "repos_url": "https://api.github.com/users/The-Compiler/repos",
        "events_url": "https://api.github.com/users/The-Compiler/events{/privacy}",
        "received_events_url": "https://api.github.com/users/The-Compiler/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 11,
    "created_at": "2016-05-29T12:35:18Z",
    "updated_at": "2016-06-03T11:34:32Z",
    "closed_at": "2016-06-01T23:55:32Z",
    "author_association": "NONE",
    "body": "Since updating from Flask 0.10.1 to 0.11.0, when trying to request `/response-headers` using [httpbin](https://github.com/Runscope/httpbin) I get:\n\n```\n[...] ERROR in app: Exception on /response-headers [GET]\nTraceback (most recent call last):\n  File \".../site-packages/flask/app.py\", line 1988, in wsgi_app\n    response = self.full_dispatch_request()\n  File \".../site-packages/flask/app.py\", line 1641, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \".../site-packages/flask/app.py\", line 1544, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \".../site-packages/flask/_compat.py\", line 33, in reraise\n    raise value\n  File \".../site-packages/flask/app.py\", line 1639, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \".../site-packages/flask/app.py\", line 1625, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \".../site-packages/httpbin/core.py\", line 314, in response_headers\n    response = jsonify(headers.lists())\n  File \".../site-packages/httpbin/core.py\", line 40, in jsonify\n    response = flask_jsonify(*args, **kwargs)\n  File \".../site-packages/flask/json.py\", line 266, in jsonify\n    (dumps(data, indent=indent, separators=separators), '\\n'),\n  File \".../site-packages/flask/json.py\", line 126, in dumps\n    rv = _json.dumps(obj, **kwargs)\n  File \".../json/__init__.py\", line 237, in dumps\n    **kw).encode(obj)\n  File \".../json/encoder.py\", line 201, in encode\n    chunks = list(chunks)\n  File \".../json/encoder.py\", line 436, in _iterencode\n    o = _default(o)\n  File \".../site-packages/flask/json.py\", line 83, in default\n    return _json.JSONEncoder.default(self, o)\n  File \".../json/encoder.py\", line 180, in default\n    raise TypeError(repr(o) + \" is not JSON serializable\")\nTypeError: <generator object MultiDict.lists at ...> is not JSON serializable\n```\n\nThis is on Python 3.5 with httpbin 0.4.1\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/222360951",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-222360951",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 222360951,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMjM2MDk1MQ==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-05-29T13:36:00Z",
            "updated_at": "2016-05-29T13:36:00Z",
            "author_association": "MEMBER",
            "body": "That appears to be a bug in httpbin when using newer Werkzeug documentations on Python 3. This line in particular:\n\n```\n  File \".../site-packages/httpbin/core.py\", line 314, in response_headers\n    response = jsonify(headers.lists())\n```\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/222440025",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-222440025",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 222440025,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMjQ0MDAyNQ==",
            "user": {
                "login": "The-Compiler",
                "id": 625793,
                "node_id": "MDQ6VXNlcjYyNTc5Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/625793?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/The-Compiler",
                "html_url": "https://github.com/The-Compiler",
                "followers_url": "https://api.github.com/users/The-Compiler/followers",
                "following_url": "https://api.github.com/users/The-Compiler/following{/other_user}",
                "gists_url": "https://api.github.com/users/The-Compiler/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/The-Compiler/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/The-Compiler/subscriptions",
                "organizations_url": "https://api.github.com/users/The-Compiler/orgs",
                "repos_url": "https://api.github.com/users/The-Compiler/repos",
                "events_url": "https://api.github.com/users/The-Compiler/events{/privacy}",
                "received_events_url": "https://api.github.com/users/The-Compiler/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-05-30T08:25:46Z",
            "updated_at": "2016-05-30T08:25:46Z",
            "author_association": "NONE",
            "body": "I don't really follow, as I only upgraded Flask and not Werkzeug and I haven't seen this before - also, it seems the [Werkzeug documentation says](http://werkzeug.pocoo.org/docs/dev/datastructures/#werkzeug.datastructures.MultiDict.lists) that `MultiDict.lists()` should return a list?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/222440350",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-222440350",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 222440350,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMjQ0MDM1MA==",
            "user": {
                "login": "ThiefMaster",
                "id": 179599,
                "node_id": "MDQ6VXNlcjE3OTU5OQ==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/179599?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ThiefMaster",
                "html_url": "https://github.com/ThiefMaster",
                "followers_url": "https://api.github.com/users/ThiefMaster/followers",
                "following_url": "https://api.github.com/users/ThiefMaster/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThiefMaster/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThiefMaster/subscriptions",
                "organizations_url": "https://api.github.com/users/ThiefMaster/orgs",
                "repos_url": "https://api.github.com/users/ThiefMaster/repos",
                "events_url": "https://api.github.com/users/ThiefMaster/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ThiefMaster/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-05-30T08:27:25Z",
            "updated_at": "2016-05-30T08:27:29Z",
            "author_association": "MEMBER",
            "body": "maybe the docs need to be updated. it does make sense for it to return an iterator in python3 though since that's what `dict.values()` etc. do\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/222441082",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-222441082",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 222441082,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMjQ0MTA4Mg==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-05-30T08:31:14Z",
            "updated_at": "2016-05-30T08:31:14Z",
            "author_association": "MEMBER",
            "body": "The behavior of all the iter-\\* methods and related ones is like dict in the respective version.\n\nIn particular, lists returns a list in Py2 and an iterator in Py3.\n\nOn 30 May 2016 10:26:00 CEST, Florian Bruhin notifications@github.com wrote:\n\n> I don't really follow, as I only upgraded Flask and not Werkzeug and I\n> haven't seen this before - also, it seems the [Werkzeug documentation\n> says](http://werkzeug.pocoo.org/docs/dev/datastructures/#werkzeug.datastructures.MultiDict.lists)\n> that `MultiDict.lists()` should return a list?\n> \n> ---\n> \n> You are receiving this because you commented.\n> Reply to this email directly or view it on GitHub:\n> https://github.com/pallets/flask/issues/1825#issuecomment-222440025\n\n## \n\nSent from my Android device with K-9 Mail. Please excuse my brevity.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/222441170",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-222441170",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 222441170,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMjQ0MTE3MA==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-05-30T08:31:40Z",
            "updated_at": "2016-05-30T08:31:40Z",
            "author_association": "MEMBER",
            "body": "And yes, the docs are a bit unfortunate right now.\n\nOn 30 May 2016 10:27:37 CEST, Adrian notifications@github.com wrote:\n\n> maybe the docs needs to be updated. it does make sense for it to return\n> an iterator in python3 though since that's what `dict.values()` etc. do\n> \n> ---\n> \n> You are receiving this because you commented.\n> Reply to this email directly or view it on GitHub:\n> https://github.com/pallets/flask/issues/1825#issuecomment-222440350\n\n## \n\nSent from my Android device with K-9 Mail. Please excuse my brevity.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/222442429",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-222442429",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 222442429,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMjQ0MjQyOQ==",
            "user": {
                "login": "The-Compiler",
                "id": 625793,
                "node_id": "MDQ6VXNlcjYyNTc5Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/625793?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/The-Compiler",
                "html_url": "https://github.com/The-Compiler",
                "followers_url": "https://api.github.com/users/The-Compiler/followers",
                "following_url": "https://api.github.com/users/The-Compiler/following{/other_user}",
                "gists_url": "https://api.github.com/users/The-Compiler/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/The-Compiler/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/The-Compiler/subscriptions",
                "organizations_url": "https://api.github.com/users/The-Compiler/orgs",
                "repos_url": "https://api.github.com/users/The-Compiler/repos",
                "events_url": "https://api.github.com/users/The-Compiler/events{/privacy}",
                "received_events_url": "https://api.github.com/users/The-Compiler/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-05-30T08:38:21Z",
            "updated_at": "2016-05-30T08:38:21Z",
            "author_association": "NONE",
            "body": "Okay - I'll open a httpbin bug then. However I still wonder why this worked before the Flask update? Did `flask.jsonify` just happen to accept generators (and convert them to lists?) and doesn't anymore with the json changes in 0.11?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/222442687",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-222442687",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 222442687,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMjQ0MjY4Nw==",
            "user": {
                "login": "ThiefMaster",
                "id": 179599,
                "node_id": "MDQ6VXNlcjE3OTU5OQ==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/179599?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ThiefMaster",
                "html_url": "https://github.com/ThiefMaster",
                "followers_url": "https://api.github.com/users/ThiefMaster/followers",
                "following_url": "https://api.github.com/users/ThiefMaster/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThiefMaster/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThiefMaster/subscriptions",
                "organizations_url": "https://api.github.com/users/ThiefMaster/orgs",
                "repos_url": "https://api.github.com/users/ThiefMaster/repos",
                "events_url": "https://api.github.com/users/ThiefMaster/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ThiefMaster/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-05-30T08:39:40Z",
            "updated_at": "2016-05-30T08:39:40Z",
            "author_association": "MEMBER",
            "body": "I think previously it did something similar to `dict(value or {}, **kwargs)` since it only accepted a single dict or kwargs anyway.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/223159354",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-223159354",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 223159354,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMzE1OTM1NA==",
            "user": {
                "login": "mitsuhiko",
                "id": 7396,
                "node_id": "MDQ6VXNlcjczOTY=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/7396?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mitsuhiko",
                "html_url": "https://github.com/mitsuhiko",
                "followers_url": "https://api.github.com/users/mitsuhiko/followers",
                "following_url": "https://api.github.com/users/mitsuhiko/following{/other_user}",
                "gists_url": "https://api.github.com/users/mitsuhiko/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mitsuhiko/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mitsuhiko/subscriptions",
                "organizations_url": "https://api.github.com/users/mitsuhiko/orgs",
                "repos_url": "https://api.github.com/users/mitsuhiko/repos",
                "events_url": "https://api.github.com/users/mitsuhiko/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mitsuhiko/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-06-01T23:55:32Z",
            "updated_at": "2016-06-01T23:55:32Z",
            "author_association": "MEMBER",
            "body": "I can't see how Flask would change this. This is an ancient change in Werkzeug itself. I suppose this might just have forced Werkzeug to update elsewhere. This also is a Python 3 specific issue in httpbin.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/223521547",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-223521547",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 223521547,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMzUyMTU0Nw==",
            "user": {
                "login": "mbra",
                "id": 641940,
                "node_id": "MDQ6VXNlcjY0MTk0MA==",
                "avatar_url": "https://avatars3.githubusercontent.com/u/641940?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mbra",
                "html_url": "https://github.com/mbra",
                "followers_url": "https://api.github.com/users/mbra/followers",
                "following_url": "https://api.github.com/users/mbra/following{/other_user}",
                "gists_url": "https://api.github.com/users/mbra/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mbra/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mbra/subscriptions",
                "organizations_url": "https://api.github.com/users/mbra/orgs",
                "repos_url": "https://api.github.com/users/mbra/repos",
                "events_url": "https://api.github.com/users/mbra/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mbra/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-06-03T08:30:58Z",
            "updated_at": "2016-06-03T08:30:58Z",
            "author_association": "NONE",
            "body": "The reasons for breaking are different on python 2 and 3, on python 2 it breaks because of https://github.com/pallets/flask/issues/1877 which might or might not be considered a Flask \"bug\".\n\nThe error on python 3 is IMHO really not something Flask can do anything about.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/223521736",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-223521736",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 223521736,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMzUyMTczNg==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-06-03T08:31:53Z",
            "updated_at": "2016-06-03T08:31:53Z",
            "author_association": "MEMBER",
            "body": "@mbra Hence the two different issues. :)\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/223556580",
            "html_url": "https://github.com/pallets/flask/issues/1825#issuecomment-223556580",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1825",
            "id": 223556580,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyMzU1NjU4MA==",
            "user": {
                "login": "The-Compiler",
                "id": 625793,
                "node_id": "MDQ6VXNlcjYyNTc5Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/625793?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/The-Compiler",
                "html_url": "https://github.com/The-Compiler",
                "followers_url": "https://api.github.com/users/The-Compiler/followers",
                "following_url": "https://api.github.com/users/The-Compiler/following{/other_user}",
                "gists_url": "https://api.github.com/users/The-Compiler/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/The-Compiler/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/The-Compiler/subscriptions",
                "organizations_url": "https://api.github.com/users/The-Compiler/orgs",
                "repos_url": "https://api.github.com/users/The-Compiler/repos",
                "events_url": "https://api.github.com/users/The-Compiler/events{/privacy}",
                "received_events_url": "https://api.github.com/users/The-Compiler/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-06-03T11:34:32Z",
            "updated_at": "2016-06-03T11:34:32Z",
            "author_association": "NONE",
            "body": "Yeah - I opened the httpbin bug and for now pinned Flask to 0.10 (with Werkzeug 0.11.10 FWIW) where this doesn't happen. :wink:\n"
        }
    ]
}