{
    "url": "https://api.github.com/repos/pallets/flask/issues/2176",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/2176/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/2176/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/2176/events",
    "html_url": "https://github.com/pallets/flask/issues/2176",
    "id": 206521121,
    "node_id": "MDU6SXNzdWUyMDY1MjExMjE=",
    "number": 2176,
    "title": "Running tests with nested objects in the data input",
    "user": {
        "login": "rth",
        "id": 630936,
        "node_id": "MDQ6VXNlcjYzMDkzNg==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/630936?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rth",
        "html_url": "https://github.com/rth",
        "followers_url": "https://api.github.com/users/rth/followers",
        "following_url": "https://api.github.com/users/rth/following{/other_user}",
        "gists_url": "https://api.github.com/users/rth/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rth/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rth/subscriptions",
        "organizations_url": "https://api.github.com/users/rth/orgs",
        "repos_url": "https://api.github.com/users/rth/repos",
        "events_url": "https://api.github.com/users/rth/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rth/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": true,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2017-02-09T14:33:33Z",
    "updated_at": "2019-11-26T16:04:53Z",
    "closed_at": "2017-02-13T12:46:23Z",
    "author_association": "NONE",
    "body": "Currently it does not seem possible to run unit-tests on endpoints that accept a nested dictionary as input when using flask with webargs / marshmallow,\r\n\r\nHere is a minimal example,\r\n```py\r\nfrom flask import Flask\r\nfrom webargs import fields\r\nfrom webargs.flaskparser import use_args\r\n\r\napp = Flask(__name__)\r\n\r\nhello_args = { \r\n    'a': fields.Nested({'name' : fields.Str()})\r\n}\r\n\r\n@app.route('/', methods=['POST'])\r\n@use_args(hello_args)\r\ndef index(args):\r\n    return 'Hello ' + str(args)\r\n\r\n\r\ndef test_app():\r\n    app.config['TESTING'] = True\r\n    test_app = app.test_client(use_cookies=False)\r\n    test_app.post(data={\"a\": {\"name\": \"Alice\"}})\r\n\r\n\r\nif __name__ == '__main__':\r\n    app.run()\r\n```\r\nwhich runs as expected,\r\n```bash\r\n% curl -H \"Content-Type: application/json\" -X POST \\\r\n       -d '{\"a\":{\"name\": \"Alice\"}}' http://localhost:5000  \r\n\r\nHello {'a': {'name': 'Alice'}}%\r\n```\r\nhowever if I try running tests on it, the argument parsing fails in `werkzeug.test.EnvironBuilder` with the following error,\r\n```\r\nnosetests test.py                                                      \r\nE\r\n======================================================================\r\nERROR: test.test_app\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/lib64/python3.4/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/tmp/test.py\", line 26, in test_app\r\n    test_app.post(data={\"a\": {\"name\": \"Alice\"}})\r\n  File \"/home/rth/.local/lib64/python3.4/site-packages/werkzeug/test.py\", line 788, in post\r\n    return self.open(*args, **kw)\r\n  File \"/home/rth/.local/lib64/python3.4/site-packages/flask/testing.py\", line 103, in open\r\n    builder = make_test_environ_builder(self.application, *args, **kwargs)\r\n  File \"/home/rth/.local/lib64/python3.4/site-packages/flask/testing.py\", line 34, in make_test_environ_builder\r\n    return EnvironBuilder(path, base_url, *args, **kwargs)\r\n  File \"/home/rth/.local/lib64/python3.4/site-packages/werkzeug/test.py\", line 338, in __init__\r\n    self._add_file_from_data(key, value)\r\n  File \"/home/rth/.local/lib64/python3.4/site-packages/werkzeug/test.py\", line 355, in _add_file_from_data\r\n    self.files.add_file(key, **value)\r\nTypeError: add_file() got multiple values for argument 'name'\r\n\r\n----------------------------------------------------------------------\r\nRan 1 test in 0.011s\r\n\r\nFAILED (errors=1)\r\n```\r\nthis uses Python 3.5, flask 0.12 and webargs 1.5.2. \r\nAny suggestions on how to address this issue (or possible workarounds) would be much appreciated.",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/279380558",
            "html_url": "https://github.com/pallets/flask/issues/2176#issuecomment-279380558",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2176",
            "id": 279380558,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI3OTM4MDU1OA==",
            "user": {
                "login": "rth",
                "id": 630936,
                "node_id": "MDQ6VXNlcjYzMDkzNg==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/630936?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rth",
                "html_url": "https://github.com/rth",
                "followers_url": "https://api.github.com/users/rth/followers",
                "following_url": "https://api.github.com/users/rth/following{/other_user}",
                "gists_url": "https://api.github.com/users/rth/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rth/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rth/subscriptions",
                "organizations_url": "https://api.github.com/users/rth/orgs",
                "repos_url": "https://api.github.com/users/rth/repos",
                "events_url": "https://api.github.com/users/rth/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rth/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2017-02-13T12:46:23Z",
            "updated_at": "2017-02-13T12:46:35Z",
            "author_association": "NONE",
            "body": "As was suggested on the pocoo IRC channel, replacing,\r\n```py\r\ntest_app.post(data={\"a\": {\"name\": \"Alice\"}})\r\n```\r\nwith \r\n```py\r\ntest_app.post(data=json.dumps({\"a\": {\"name\": \"Alice\"}}),\r\n                content_type='application/json')\r\n```\r\nfixes this problem (also related SO answers [here](https://stackoverflow.com/questions/28836893/how-to-send-requests-with-jsons-in-unit-tests)). "
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/532495906",
            "html_url": "https://github.com/pallets/flask/issues/2176#issuecomment-532495906",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2176",
            "id": 532495906,
            "node_id": "MDEyOklzc3VlQ29tbWVudDUzMjQ5NTkwNg==",
            "user": {
                "login": "toonarmycaptain",
                "id": 29956894,
                "node_id": "MDQ6VXNlcjI5OTU2ODk0",
                "avatar_url": "https://avatars3.githubusercontent.com/u/29956894?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/toonarmycaptain",
                "html_url": "https://github.com/toonarmycaptain",
                "followers_url": "https://api.github.com/users/toonarmycaptain/followers",
                "following_url": "https://api.github.com/users/toonarmycaptain/following{/other_user}",
                "gists_url": "https://api.github.com/users/toonarmycaptain/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/toonarmycaptain/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/toonarmycaptain/subscriptions",
                "organizations_url": "https://api.github.com/users/toonarmycaptain/orgs",
                "repos_url": "https://api.github.com/users/toonarmycaptain/repos",
                "events_url": "https://api.github.com/users/toonarmycaptain/events{/privacy}",
                "received_events_url": "https://api.github.com/users/toonarmycaptain/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-09-18T02:50:43Z",
            "updated_at": "2019-09-18T02:50:43Z",
            "author_association": "NONE",
            "body": "I'm having trouble with this issue too. Possibly because the data I'm passing is to be interpreted as forms which are nested, dumping to json and setting the content_type as such doesn't work, or at least doesn't place the data in my forms as I need it to be when the request is processed. "
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/558691904",
            "html_url": "https://github.com/pallets/flask/issues/2176#issuecomment-558691904",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2176",
            "id": 558691904,
            "node_id": "MDEyOklzc3VlQ29tbWVudDU1ODY5MTkwNA==",
            "user": {
                "login": "austinhoag",
                "id": 42473349,
                "node_id": "MDQ6VXNlcjQyNDczMzQ5",
                "avatar_url": "https://avatars0.githubusercontent.com/u/42473349?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/austinhoag",
                "html_url": "https://github.com/austinhoag",
                "followers_url": "https://api.github.com/users/austinhoag/followers",
                "following_url": "https://api.github.com/users/austinhoag/following{/other_user}",
                "gists_url": "https://api.github.com/users/austinhoag/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/austinhoag/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/austinhoag/subscriptions",
                "organizations_url": "https://api.github.com/users/austinhoag/orgs",
                "repos_url": "https://api.github.com/users/austinhoag/repos",
                "events_url": "https://api.github.com/users/austinhoag/events{/privacy}",
                "received_events_url": "https://api.github.com/users/austinhoag/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-11-26T15:50:20Z",
            "updated_at": "2019-11-26T15:50:20Z",
            "author_association": "NONE",
            "body": "I also have the same issue as toonarmycaption. The above fix does not work for me."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/558698464",
            "html_url": "https://github.com/pallets/flask/issues/2176#issuecomment-558698464",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2176",
            "id": 558698464,
            "node_id": "MDEyOklzc3VlQ29tbWVudDU1ODY5ODQ2NA==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-11-26T16:04:42Z",
            "updated_at": "2019-11-26T16:04:42Z",
            "author_association": "MEMBER",
            "body": "https://github.com/pallets/werkzeug/issues/1646\r\n\r\n> Form data is not nestable, it's always sent as a flat list of keys/values. WTForms accomplishes nesting by applying prefixes to the keys so that it can reconstruct the nesting after loading the flat data. You'll need to provide this same flat data. If you're not using WTForms to read the data (the middle portion of your post), you need to access the same flat keys, Werkzeug doesn't parse it into a nested structure."
        }
    ]
}