{
    "url": "https://api.github.com/repos/pallets/flask/issues/2574",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/2574/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/2574/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/2574/events",
    "html_url": "https://github.com/pallets/flask/issues/2574",
    "id": 285404778,
    "node_id": "MDU6SXNzdWUyODU0MDQ3Nzg=",
    "number": 2574,
    "title": "Can't install flask on windows 10 ",
    "user": {
        "login": "tibetegya",
        "id": 13131669,
        "node_id": "MDQ6VXNlcjEzMTMxNjY5",
        "avatar_url": "https://avatars1.githubusercontent.com/u/13131669?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tibetegya",
        "html_url": "https://github.com/tibetegya",
        "followers_url": "https://api.github.com/users/tibetegya/followers",
        "following_url": "https://api.github.com/users/tibetegya/following{/other_user}",
        "gists_url": "https://api.github.com/users/tibetegya/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tibetegya/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tibetegya/subscriptions",
        "organizations_url": "https://api.github.com/users/tibetegya/orgs",
        "repos_url": "https://api.github.com/users/tibetegya/repos",
        "events_url": "https://api.github.com/users/tibetegya/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tibetegya/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2018-01-02T11:10:23Z",
    "updated_at": "2018-01-02T12:01:03Z",
    "closed_at": "2018-01-02T12:01:03Z",
    "author_association": "NONE",
    "body": "Below is what i get when i try to install it\r\n\r\n```\r\nC:\\Users\\TIBZY>pip install flask\r\nCollecting flask\r\n  Using cached Flask-0.12.2-py2.py3-none-any.whl\r\nCollecting itsdangerous>=0.21 (from flask)\r\n  Using cached itsdangerous-0.24.tar.gz\r\n    Complete output from command python setup.py egg_info:\r\n    running egg_info\r\n    creating pip-egg-info\\itsdangerous.egg-info\r\n    writing pip-egg-info\\itsdangerous.egg-info\\PKG-INFO\r\n    writing dependency_links to pip-egg-info\\itsdangerous.egg-info\\dependency_links.txt\r\n    writing top-level names to pip-egg-info\\itsdangerous.egg-info\\top_level.txt\r\n    writing manifest file 'pip-egg-info\\itsdangerous.egg-info\\SOURCES.txt'\r\n    error: [Errno 2] No such file or directory: 'c:\\\\users\\\\tibzy\\\\python36\\\\python36.zip\\\\lib2to3\\\\Grammar.txt'\r\n\r\n    ----------------------------------------\r\nCommand \"python setup.py egg_info\" failed with error code 1 in C:\\Users\\TIBZY\\AppData\\Local\\Temp\\pip-build-az__2i6f\\itsdangerous\\\r\n```",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/354750121",
            "html_url": "https://github.com/pallets/flask/issues/2574#issuecomment-354750121",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2574",
            "id": 354750121,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM1NDc1MDEyMQ==",
            "user": {
                "login": "ThiefMaster",
                "id": 179599,
                "node_id": "MDQ6VXNlcjE3OTU5OQ==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/179599?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ThiefMaster",
                "html_url": "https://github.com/ThiefMaster",
                "followers_url": "https://api.github.com/users/ThiefMaster/followers",
                "following_url": "https://api.github.com/users/ThiefMaster/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThiefMaster/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThiefMaster/subscriptions",
                "organizations_url": "https://api.github.com/users/ThiefMaster/orgs",
                "repos_url": "https://api.github.com/users/ThiefMaster/repos",
                "events_url": "https://api.github.com/users/ThiefMaster/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ThiefMaster/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-01-02T11:43:25Z",
            "updated_at": "2018-01-02T11:43:25Z",
            "author_association": "MEMBER",
            "body": "That sounds much more like something is wrong with your Python environment."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/354752660",
            "html_url": "https://github.com/pallets/flask/issues/2574#issuecomment-354752660",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2574",
            "id": 354752660,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM1NDc1MjY2MA==",
            "user": {
                "login": "tibetegya",
                "id": 13131669,
                "node_id": "MDQ6VXNlcjEzMTMxNjY5",
                "avatar_url": "https://avatars1.githubusercontent.com/u/13131669?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/tibetegya",
                "html_url": "https://github.com/tibetegya",
                "followers_url": "https://api.github.com/users/tibetegya/followers",
                "following_url": "https://api.github.com/users/tibetegya/following{/other_user}",
                "gists_url": "https://api.github.com/users/tibetegya/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/tibetegya/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tibetegya/subscriptions",
                "organizations_url": "https://api.github.com/users/tibetegya/orgs",
                "repos_url": "https://api.github.com/users/tibetegya/repos",
                "events_url": "https://api.github.com/users/tibetegya/events{/privacy}",
                "received_events_url": "https://api.github.com/users/tibetegya/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-01-02T12:00:46Z",
            "updated_at": "2018-01-02T12:00:46Z",
            "author_association": "NONE",
            "body": "you are right i have reinstalled python its now fine"
        }
    ]
}