{
    "url": "https://api.github.com/repos/pallets/flask/issues/2801",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/2801/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/2801/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/2801/events",
    "html_url": "https://github.com/pallets/flask/issues/2801",
    "id": 326748605,
    "node_id": "MDU6SXNzdWUzMjY3NDg2MDU=",
    "number": 2801,
    "title": "AttributeError: 'FileWrapper' due to click",
    "user": {
        "login": "2press",
        "id": 26044736,
        "node_id": "MDQ6VXNlcjI2MDQ0NzM2",
        "avatar_url": "https://avatars2.githubusercontent.com/u/26044736?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/2press",
        "html_url": "https://github.com/2press",
        "followers_url": "https://api.github.com/users/2press/followers",
        "following_url": "https://api.github.com/users/2press/following{/other_user}",
        "gists_url": "https://api.github.com/users/2press/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/2press/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/2press/subscriptions",
        "organizations_url": "https://api.github.com/users/2press/orgs",
        "repos_url": "https://api.github.com/users/2press/repos",
        "events_url": "https://api.github.com/users/2press/events{/privacy}",
        "received_events_url": "https://api.github.com/users/2press/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2018-05-26T16:03:18Z",
    "updated_at": "2018-05-26T17:22:16Z",
    "closed_at": "2018-05-26T17:22:16Z",
    "author_association": "NONE",
    "body": "Since a few days I am facing this error when running `Flask.run()` caused by `click` on Windows 10.0.17134 with Python 3.6.5, flask 1.0.2 and click6.7:\r\n```\r\nTraceback (most recent call last):\r\n  File \"D:\\Code\\GitHub\\StarCraft-Casting-Tool\\scctool\\tasks\\webapp.py\", line 189, in run\r\n    self.application.run(port=65010)\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\flask\\app.py\", line 938, in run\r\n    cli.show_server_banner(self.env, self.debug, self.name, False)\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\flask\\cli.py\", line 629, in show_server_banner\r\n    click.echo(message)\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\click\\utils.py\", line 217, in echo\r\n    file = _default_text_stdout()\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\click\\_compat.py\", line 621, in func\r\n    rv = wrapper_func()\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\click\\_compat.py\", line 385, in get_text_stdout\r\n    rv = _get_windows_console_stream(sys.stdout, encoding, errors)\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\click\\_winconsole.py\", line 264, in _get_windows_console_stream\r\n    f = getattr(f, 'buffer')\r\nAttributeError: 'FileWrapper' object has no attribute 'buffer'\r\n```\r\n\r\nCan anybody help me?",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/392271619",
            "html_url": "https://github.com/pallets/flask/issues/2801#issuecomment-392271619",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2801",
            "id": 392271619,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5MjI3MTYxOQ==",
            "user": {
                "login": "2press",
                "id": 26044736,
                "node_id": "MDQ6VXNlcjI2MDQ0NzM2",
                "avatar_url": "https://avatars2.githubusercontent.com/u/26044736?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/2press",
                "html_url": "https://github.com/2press",
                "followers_url": "https://api.github.com/users/2press/followers",
                "following_url": "https://api.github.com/users/2press/following{/other_user}",
                "gists_url": "https://api.github.com/users/2press/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/2press/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/2press/subscriptions",
                "organizations_url": "https://api.github.com/users/2press/orgs",
                "repos_url": "https://api.github.com/users/2press/repos",
                "events_url": "https://api.github.com/users/2press/events{/privacy}",
                "received_events_url": "https://api.github.com/users/2press/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-05-26T16:18:05Z",
            "updated_at": "2018-05-26T16:18:05Z",
            "author_association": "NONE",
            "body": "Fixed by updating click to the latest unreleased master branch."
        }
    ]
}