{
    "url": "https://api.github.com/repos/pallets/flask/issues/2983",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/2983/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/2983/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/2983/events",
    "html_url": "https://github.com/pallets/flask/pull/2983",
    "id": 376519065,
    "node_id": "MDExOlB1bGxSZXF1ZXN0MjI3NzE4OTc5",
    "number": 2983,
    "title": "Don't pass unexpected exception types to error handlers",
    "user": {
        "login": "taion",
        "id": 3112159,
        "node_id": "MDQ6VXNlcjMxMTIxNTk=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/3112159?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/taion",
        "html_url": "https://github.com/taion",
        "followers_url": "https://api.github.com/users/taion/followers",
        "following_url": "https://api.github.com/users/taion/following{/other_user}",
        "gists_url": "https://api.github.com/users/taion/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/taion/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/taion/subscriptions",
        "organizations_url": "https://api.github.com/users/taion/orgs",
        "repos_url": "https://api.github.com/users/taion/repos",
        "events_url": "https://api.github.com/users/taion/events{/privacy}",
        "received_events_url": "https://api.github.com/users/taion/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 9,
    "created_at": "2018-11-01T18:42:49Z",
    "updated_at": "2019-06-21T02:38:17Z",
    "closed_at": "2019-06-19T23:05:04Z",
    "author_association": "CONTRIBUTOR",
    "pull_request": {
        "url": "https://api.github.com/repos/pallets/flask/pulls/2983",
        "html_url": "https://github.com/pallets/flask/pull/2983",
        "diff_url": "https://github.com/pallets/flask/pull/2983.diff",
        "patch_url": "https://github.com/pallets/flask/pull/2983.patch"
    },
    "body": "Fixes https://github.com/pallets/flask/issues/2778\n\ncc @ThiefMaster\n\nThis follows my last proposal in https://github.com/pallets/flask/issues/2778#issuecomment-435130792.",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/437918932",
            "html_url": "https://github.com/pallets/flask/pull/2983#issuecomment-437918932",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2983",
            "id": 437918932,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzNzkxODkzMg==",
            "user": {
                "login": "garenchan",
                "id": 13200012,
                "node_id": "MDQ6VXNlcjEzMjAwMDEy",
                "avatar_url": "https://avatars2.githubusercontent.com/u/13200012?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/garenchan",
                "html_url": "https://github.com/garenchan",
                "followers_url": "https://api.github.com/users/garenchan/followers",
                "following_url": "https://api.github.com/users/garenchan/following{/other_user}",
                "gists_url": "https://api.github.com/users/garenchan/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/garenchan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/garenchan/subscriptions",
                "organizations_url": "https://api.github.com/users/garenchan/orgs",
                "repos_url": "https://api.github.com/users/garenchan/repos",
                "events_url": "https://api.github.com/users/garenchan/events{/privacy}",
                "received_events_url": "https://api.github.com/users/garenchan/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-11-12T15:19:14Z",
            "updated_at": "2018-11-12T15:19:14Z",
            "author_association": "CONTRIBUTOR",
            "body": "Like you, I think the current implementation is a bit confusing.\r\n\r\nBut at least we can get the original error in the handler. This is useful for both logging and troubleshooting errors. But your solution doesn't take this into account. "
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/437919918",
            "html_url": "https://github.com/pallets/flask/pull/2983#issuecomment-437919918",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2983",
            "id": 437919918,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzNzkxOTkxOA==",
            "user": {
                "login": "taion",
                "id": 3112159,
                "node_id": "MDQ6VXNlcjMxMTIxNTk=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/3112159?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/taion",
                "html_url": "https://github.com/taion",
                "followers_url": "https://api.github.com/users/taion/followers",
                "following_url": "https://api.github.com/users/taion/following{/other_user}",
                "gists_url": "https://api.github.com/users/taion/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/taion/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/taion/subscriptions",
                "organizations_url": "https://api.github.com/users/taion/orgs",
                "repos_url": "https://api.github.com/users/taion/repos",
                "events_url": "https://api.github.com/users/taion/events{/privacy}",
                "received_events_url": "https://api.github.com/users/taion/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-11-12T15:21:55Z",
            "updated_at": "2018-11-12T15:21:55Z",
            "author_association": "CONTRIBUTOR",
            "body": "Perhaps `InternalServerError` should be tagged with the original error.\r\n\r\nNote, though, that the implementation above _will_ forward the original error when the error handler is installed on `500`."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/437923334",
            "html_url": "https://github.com/pallets/flask/pull/2983#issuecomment-437923334",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2983",
            "id": 437923334,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzNzkyMzMzNA==",
            "user": {
                "login": "garenchan",
                "id": 13200012,
                "node_id": "MDQ6VXNlcjEzMjAwMDEy",
                "avatar_url": "https://avatars2.githubusercontent.com/u/13200012?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/garenchan",
                "html_url": "https://github.com/garenchan",
                "followers_url": "https://api.github.com/users/garenchan/followers",
                "following_url": "https://api.github.com/users/garenchan/following{/other_user}",
                "gists_url": "https://api.github.com/users/garenchan/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/garenchan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/garenchan/subscriptions",
                "organizations_url": "https://api.github.com/users/garenchan/orgs",
                "repos_url": "https://api.github.com/users/garenchan/repos",
                "events_url": "https://api.github.com/users/garenchan/events{/privacy}",
                "received_events_url": "https://api.github.com/users/garenchan/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-11-12T15:31:04Z",
            "updated_at": "2018-11-12T15:31:34Z",
            "author_association": "CONTRIBUTOR",
            "body": "I'm sorry to have misunderstood your solution. I think a test case for the handler of `InternalServerError`  can help us understand your solution more easily."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/437924249",
            "html_url": "https://github.com/pallets/flask/pull/2983#issuecomment-437924249",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2983",
            "id": 437924249,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzNzkyNDI0OQ==",
            "user": {
                "login": "taion",
                "id": 3112159,
                "node_id": "MDQ6VXNlcjMxMTIxNTk=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/3112159?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/taion",
                "html_url": "https://github.com/taion",
                "followers_url": "https://api.github.com/users/taion/followers",
                "following_url": "https://api.github.com/users/taion/following{/other_user}",
                "gists_url": "https://api.github.com/users/taion/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/taion/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/taion/subscriptions",
                "organizations_url": "https://api.github.com/users/taion/orgs",
                "repos_url": "https://api.github.com/users/taion/repos",
                "events_url": "https://api.github.com/users/taion/events{/privacy}",
                "received_events_url": "https://api.github.com/users/taion/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-11-12T15:33:31Z",
            "updated_at": "2018-11-12T15:33:31Z",
            "author_association": "CONTRIBUTOR",
            "body": "This assertion is actually already present in https://github.com/pallets/flask/blob/92964b429bd89d48146e32107983de43a71a738a/tests/test_user_error_handler.py#L43."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/437926465",
            "html_url": "https://github.com/pallets/flask/pull/2983#issuecomment-437926465",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2983",
            "id": 437926465,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzNzkyNjQ2NQ==",
            "user": {
                "login": "garenchan",
                "id": 13200012,
                "node_id": "MDQ6VXNlcjEzMjAwMDEy",
                "avatar_url": "https://avatars2.githubusercontent.com/u/13200012?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/garenchan",
                "html_url": "https://github.com/garenchan",
                "followers_url": "https://api.github.com/users/garenchan/followers",
                "following_url": "https://api.github.com/users/garenchan/following{/other_user}",
                "gists_url": "https://api.github.com/users/garenchan/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/garenchan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/garenchan/subscriptions",
                "organizations_url": "https://api.github.com/users/garenchan/orgs",
                "repos_url": "https://api.github.com/users/garenchan/repos",
                "events_url": "https://api.github.com/users/garenchan/events{/privacy}",
                "received_events_url": "https://api.github.com/users/garenchan/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-11-12T15:39:46Z",
            "updated_at": "2018-11-12T15:39:46Z",
            "author_association": "CONTRIBUTOR",
            "body": "Oh, I see. I only read the codes in your patch. Please forgive me for wasting your precious time!"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/437935008",
            "html_url": "https://github.com/pallets/flask/pull/2983#issuecomment-437935008",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2983",
            "id": 437935008,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzNzkzNTAwOA==",
            "user": {
                "login": "taion",
                "id": 3112159,
                "node_id": "MDQ6VXNlcjMxMTIxNTk=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/3112159?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/taion",
                "html_url": "https://github.com/taion",
                "followers_url": "https://api.github.com/users/taion/followers",
                "following_url": "https://api.github.com/users/taion/following{/other_user}",
                "gists_url": "https://api.github.com/users/taion/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/taion/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/taion/subscriptions",
                "organizations_url": "https://api.github.com/users/taion/orgs",
                "repos_url": "https://api.github.com/users/taion/repos",
                "events_url": "https://api.github.com/users/taion/events{/privacy}",
                "received_events_url": "https://api.github.com/users/taion/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-11-12T16:03:09Z",
            "updated_at": "2018-11-12T16:03:09Z",
            "author_association": "CONTRIBUTOR",
            "body": "I mean, now that you mention it, though, I do think it would be a better API if `InternalServerError` had some reference to the actual original exception. That would likely constitute a breaking API change, though, whereas this might just barely be okay."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/437940494",
            "html_url": "https://github.com/pallets/flask/pull/2983#issuecomment-437940494",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2983",
            "id": 437940494,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzNzk0MDQ5NA==",
            "user": {
                "login": "garenchan",
                "id": 13200012,
                "node_id": "MDQ6VXNlcjEzMjAwMDEy",
                "avatar_url": "https://avatars2.githubusercontent.com/u/13200012?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/garenchan",
                "html_url": "https://github.com/garenchan",
                "followers_url": "https://api.github.com/users/garenchan/followers",
                "following_url": "https://api.github.com/users/garenchan/following{/other_user}",
                "gists_url": "https://api.github.com/users/garenchan/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/garenchan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/garenchan/subscriptions",
                "organizations_url": "https://api.github.com/users/garenchan/orgs",
                "repos_url": "https://api.github.com/users/garenchan/repos",
                "events_url": "https://api.github.com/users/garenchan/events{/privacy}",
                "received_events_url": "https://api.github.com/users/garenchan/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-11-12T16:18:47Z",
            "updated_at": "2018-11-12T16:18:47Z",
            "author_association": "CONTRIBUTOR",
            "body": "Yes, I quite agree with you. \r\n\r\n> Perhaps InternalServerError should be tagged with the original error."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/451194839",
            "html_url": "https://github.com/pallets/flask/pull/2983#issuecomment-451194839",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2983",
            "id": 451194839,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ1MTE5NDgzOQ==",
            "user": {
                "login": "taion",
                "id": 3112159,
                "node_id": "MDQ6VXNlcjMxMTIxNTk=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/3112159?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/taion",
                "html_url": "https://github.com/taion",
                "followers_url": "https://api.github.com/users/taion/followers",
                "following_url": "https://api.github.com/users/taion/following{/other_user}",
                "gists_url": "https://api.github.com/users/taion/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/taion/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/taion/subscriptions",
                "organizations_url": "https://api.github.com/users/taion/orgs",
                "repos_url": "https://api.github.com/users/taion/repos",
                "events_url": "https://api.github.com/users/taion/events{/privacy}",
                "received_events_url": "https://api.github.com/users/taion/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-01-03T16:22:29Z",
            "updated_at": "2019-01-07T15:24:55Z",
            "author_association": "CONTRIBUTOR",
            "body": "Any thoughts here?"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/503778246",
            "html_url": "https://github.com/pallets/flask/pull/2983#issuecomment-503778246",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2983",
            "id": 503778246,
            "node_id": "MDEyOklzc3VlQ29tbWVudDUwMzc3ODI0Ng==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-06-19T23:05:04Z",
            "updated_at": "2019-06-19T23:05:17Z",
            "author_association": "MEMBER",
            "body": "While I understand the results of this, it's making the code harder to follow for me. Based on previous discussions in PRs that led to where we are now, it seems that it was intended that 500 and `InternalServerError` were aliases that behave the same way.\r\n\r\nInstead, based on your discussions, I went the other direction and made it consistent. `500` and `InternalServerError` handlers always received `InternalServerError`, and also add an `original_exception` attribute. While this could result in some less-specific generic error messages if an application with the old behavior upgrades, I think the behavior becoming easier to reason about is worth it.\r\n\r\nThanks for discussing and working on this! Closing in favor of #3266 "
        }
    ]
}