{
    "url": "https://api.github.com/repos/pallets/flask/issues/3020",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/3020/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/3020/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/3020/events",
    "html_url": "https://github.com/pallets/flask/issues/3020",
    "id": 388864706,
    "node_id": "MDU6SXNzdWUzODg4NjQ3MDY=",
    "number": 3020,
    "title": "Build error when using url_for(request.endpoint)",
    "user": {
        "login": "brenwickham",
        "id": 35278345,
        "node_id": "MDQ6VXNlcjM1Mjc4MzQ1",
        "avatar_url": "https://avatars0.githubusercontent.com/u/35278345?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/brenwickham",
        "html_url": "https://github.com/brenwickham",
        "followers_url": "https://api.github.com/users/brenwickham/followers",
        "following_url": "https://api.github.com/users/brenwickham/following{/other_user}",
        "gists_url": "https://api.github.com/users/brenwickham/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/brenwickham/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/brenwickham/subscriptions",
        "organizations_url": "https://api.github.com/users/brenwickham/orgs",
        "repos_url": "https://api.github.com/users/brenwickham/repos",
        "events_url": "https://api.github.com/users/brenwickham/events{/privacy}",
        "received_events_url": "https://api.github.com/users/brenwickham/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2018-12-08T00:46:56Z",
    "updated_at": "2018-12-08T00:49:35Z",
    "closed_at": "2018-12-08T00:48:37Z",
    "author_association": "NONE",
    "body": "### Expected Behavior\r\nI put this IF statement in my base.html template:\r\n\r\n```html\r\n    {% if \"dashboard\" in url_for(request.endpoint)  %}\r\n    <script src={{ url_for('static', filename='js/dashboard.js') }}></script>\r\n    {% endif %}\r\n```\r\nI added an endpoint with a value. For example: \r\n```python\r\n@app.route(\"/accountmgmt/<int:userid>\",methods=[\"GET\",\"POST\"])\r\n@login_required\r\ndef accountmgmt(userid):\r\n   ... etc\r\n```\r\n\r\n### Actual Behavior\r\nThe above code causes a build error, but only when an endpoint has a value (as above). \r\n\r\nWhen I remove the above IF statement from the template, the code does not error. But when it is included, I get this error (I am using the URL: http://127.0.0.1:5000/accountmgmt/123):\r\n\r\n```pytb\r\nCould not build url for endpoint 'accountmgmt'. Did you forget to specify values ['userid']?\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/app.py\", line 2309, in __call__\r\nreturn self.wsgi_app(environ, start_response)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/app.py\", line 2295, in wsgi_app\r\nresponse = self.handle_exception(e)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/app.py\", line 1741, in handle_exception\r\nreraise(exc_type, exc_value, tb)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/_compat.py\", line 35, in reraise\r\nraise value\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/app.py\", line 2292, in wsgi_app\r\nresponse = self.full_dispatch_request()\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/app.py\", line 1815, in full_dispatch_request\r\nrv = self.handle_user_exception(e)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/app.py\", line 1718, in handle_user_exception\r\nreraise(exc_type, exc_value, tb)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/_compat.py\", line 35, in reraise\r\nraise value\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/app.py\", line 1813, in full_dispatch_request\r\nrv = self.dispatch_request()\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/app.py\", line 1799, in dispatch_request\r\nreturn self.view_functions[rule.endpoint](**req.view_args)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask_login/utils.py\", line 261, in decorated_view\r\nreturn func(*args, **kwargs)\r\nFile \"/Users/brendon/dev/nelliedata/nellieapp/routes.py\", line 43, in accountmgmt\r\nreturn render_template(\"accountmgmt.html\",users=userlist, current_user=current_user,title=\"Nellie Data: Account Management\")\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/templating.py\", line 135, in render_template\r\ncontext, ctx.app)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/templating.py\", line 117, in _render\r\nrv = template.render(context)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/jinja2/asyncsupport.py\", line 76, in render\r\nreturn original_render(self, *args, **kwargs)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/jinja2/environment.py\", line 1008, in render\r\nreturn self.environment.handle_exception(exc_info, True)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/jinja2/environment.py\", line 780, in handle_exception\r\nreraise(exc_type, exc_value, tb)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/jinja2/_compat.py\", line 37, in reraise\r\nraise value.with_traceback(tb)\r\nFile \"/Users/brendon/dev/nelliedata/nellieapp/templates/accountmgmt.html\", line 1, in top-level template code\r\n{% extends \"base.html\" %}\r\nFile \"/Users/brendon/dev/nelliedata/nellieapp/templates/base.html\", line 115, in top-level template code\r\n{% if \"test\" in url_for(request.endpoint)  %}\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/helpers.py\", line 356, in url_for\r\nreturn appctx.app.handle_url_build_error(error, endpoint, values)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/app.py\", line 2061, in handle_url_build_error\r\nreraise(exc_type, exc_value, tb)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/_compat.py\", line 35, in reraise\r\nraise value\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/flask/helpers.py\", line 345, in url_for\r\nforce_external=external)\r\nFile \"/Users/brendon/dev/nelliedata/flask/lib/python3.6/site-packages/werkzeug/routing.py\", line 1776, in build\r\nraise BuildError(endpoint, values, method, self)\r\nwerkzeug.routing.BuildError: Could not build url for endpoint 'accountmgmt'. Did you forget to specify values ['userid']?\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.5\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/445414035",
            "html_url": "https://github.com/pallets/flask/issues/3020#issuecomment-445414035",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/3020",
            "id": 445414035,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ0NTQxNDAzNQ==",
            "user": {
                "login": "ThiefMaster",
                "id": 179599,
                "node_id": "MDQ6VXNlcjE3OTU5OQ==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/179599?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ThiefMaster",
                "html_url": "https://github.com/ThiefMaster",
                "followers_url": "https://api.github.com/users/ThiefMaster/followers",
                "following_url": "https://api.github.com/users/ThiefMaster/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThiefMaster/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThiefMaster/subscriptions",
                "organizations_url": "https://api.github.com/users/ThiefMaster/orgs",
                "repos_url": "https://api.github.com/users/ThiefMaster/repos",
                "events_url": "https://api.github.com/users/ThiefMaster/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ThiefMaster/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-12-08T00:48:37Z",
            "updated_at": "2018-12-08T00:49:35Z",
            "author_association": "MEMBER",
            "body": "Well that's because you are not supposed to use `url_for` like this. If you want to check if the user is on a certain page, check if `request.endpoint == 'dashboard'` or whatever the name of your dashboard's endpoint is.\r\n\r\nPS: Please use Stack Overflow or IRC for questions like this."
        }
    ]
}